spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/pg_theater
spring.datasource.username=backend
spring.datasource.password=backend
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
